/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedLegalRouteImport } from './routes/_authenticated/legal'
import { Route as AuthenticatedEarlyWarningRouteImport } from './routes/_authenticated/early-warning'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedCollateralRouteImport } from './routes/_authenticated/collateral'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgingRouteImport } from './routes/_authenticated/aging'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCoreBankingCustomerNationalIdRouteImport } from './routes/api/public/core-banking/customer.$nationalId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegalRoute = AuthenticatedLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarlyWarningRoute =
  AuthenticatedEarlyWarningRouteImport.update({
    id: '/early-warning',
    path: '/early-warning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollateralRoute = AuthenticatedCollateralRouteImport.update({
  id: '/collateral',
  path: '/collateral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgingRoute = AuthenticatedAgingRouteImport.update({
  id: '/aging',
  path: '/aging',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCoreBankingCustomerNationalIdRoute =
  ApiPublicCoreBankingCustomerNationalIdRouteImport.update({
    id: '/api/public/core-banking/customer/$nationalId',
    path: '/api/public/core-banking/customer/$nationalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aging': typeof AuthenticatedAgingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/collateral': typeof AuthenticatedCollateralRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/early-warning': typeof AuthenticatedEarlyWarningRoute
  '/legal': typeof AuthenticatedLegalRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/api/public/core-banking/customer/$nationalId': typeof ApiPublicCoreBankingCustomerNationalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aging': typeof AuthenticatedAgingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/collateral': typeof AuthenticatedCollateralRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/early-warning': typeof AuthenticatedEarlyWarningRoute
  '/legal': typeof AuthenticatedLegalRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/api/public/core-banking/customer/$nationalId': typeof ApiPublicCoreBankingCustomerNationalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aging': typeof AuthenticatedAgingRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/collateral': typeof AuthenticatedCollateralRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/early-warning': typeof AuthenticatedEarlyWarningRoute
  '/_authenticated/legal': typeof AuthenticatedLegalRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/api/public/core-banking/customer/$nationalId': typeof ApiPublicCoreBankingCustomerNationalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/aging'
    | '/analytics'
    | '/collateral'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/early-warning'
    | '/legal'
    | '/loans'
    | '/notifications'
    | '/reports'
    | '/risk'
    | '/api/public/core-banking/customer/$nationalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/aging'
    | '/analytics'
    | '/collateral'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/early-warning'
    | '/legal'
    | '/loans'
    | '/notifications'
    | '/reports'
    | '/risk'
    | '/api/public/core-banking/customer/$nationalId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/aging'
    | '/_authenticated/analytics'
    | '/_authenticated/collateral'
    | '/_authenticated/collections'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/early-warning'
    | '/_authenticated/legal'
    | '/_authenticated/loans'
    | '/_authenticated/notifications'
    | '/_authenticated/reports'
    | '/_authenticated/risk'
    | '/api/public/core-banking/customer/$nationalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicCoreBankingCustomerNationalIdRoute: typeof ApiPublicCoreBankingCustomerNationalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal': {
      id: '/_authenticated/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AuthenticatedLegalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/early-warning': {
      id: '/_authenticated/early-warning'
      path: '/early-warning'
      fullPath: '/early-warning'
      preLoaderRoute: typeof AuthenticatedEarlyWarningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collateral': {
      id: '/_authenticated/collateral'
      path: '/collateral'
      fullPath: '/collateral'
      preLoaderRoute: typeof AuthenticatedCollateralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aging': {
      id: '/_authenticated/aging'
      path: '/aging'
      fullPath: '/aging'
      preLoaderRoute: typeof AuthenticatedAgingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/core-banking/customer/$nationalId': {
      id: '/api/public/core-banking/customer/$nationalId'
      path: '/api/public/core-banking/customer/$nationalId'
      fullPath: '/api/public/core-banking/customer/$nationalId'
      preLoaderRoute: typeof ApiPublicCoreBankingCustomerNationalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgingRoute: typeof AuthenticatedAgingRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCollateralRoute: typeof AuthenticatedCollateralRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEarlyWarningRoute: typeof AuthenticatedEarlyWarningRoute
  AuthenticatedLegalRoute: typeof AuthenticatedLegalRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgingRoute: AuthenticatedAgingRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCollateralRoute: AuthenticatedCollateralRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEarlyWarningRoute: AuthenticatedEarlyWarningRoute,
  AuthenticatedLegalRoute: AuthenticatedLegalRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicCoreBankingCustomerNationalIdRoute:
    ApiPublicCoreBankingCustomerNationalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
